"""Stage 8: generate slide text + caption from the VALIDATED evidence
matrix only (product spec §16 Content Generator, §6 caption format).
Source names/URLs in the caption are assembled from `sources` rows in
code, never generated by the LLM — see schemas/content.py."""

from app.core.config import get_settings
from app.core.logging import get_logger
from app.db.models import ActorType, Claim, Evidence, Reel, Source, Verdict
from app.pipeline.audit import record_audit
from app.schemas.content import ContentGenerationResult
from app.services.ai.base import LLMCallResult
from app.services.ai.factory import get_llm_provider
from app.services.ai.prompts import CONTENT_GENERATION_PROMPT_VERSION, CONTENT_GENERATION_SYSTEM_PROMPT

logger = get_logger(__name__)

_MAX_CAPTION_SOURCES = 5
_HASHTAGS = "#FactCheck #MediaLiteracy #TruthLens"

_IMPORTANT_NOTE = (
    "This fact-check evaluates the specific claim made in the referenced reel "
    "based on the evidence available at the time of publication."
)

# Same "schema-valid but empty" failure mode observed in claim_extraction
# (ARCHITECTURE §8), seen live in content_generation too: Ollama returned
# every one of these fields as "" for a real UNVERIFIED verdict, even
# though the same model produces real copy for UNVERIFIED verdicts when
# it isn't failing (the prompt explicitly allows "we could not confirm
# this claim" language — empty string is never a legitimate answer here).
_REQUIRED_NONEMPTY_FIELDS = (
    "slide1_claim_summary",
    "slide3_evidence_explanation",
    "slide3_key_fact",
    "slide4_conclusion_paragraph",
    "caption_what_we_found",
    "caption_why",
)


def _content_looks_complete(generated: ContentGenerationResult) -> bool:
    return all(getattr(generated, field).strip() for field in _REQUIRED_NONEMPTY_FIELDS)


def _top_sources_for_caption(evidence_rows: list[Evidence], sources_by_id: dict[object, Source]) -> list[Source]:
    cited = [sources_by_id[e.source_id] for e in evidence_rows if e.stance.value in ("supports", "contradicts")]
    cited.sort(key=lambda s: s.reliability_score, reverse=True)
    # de-dupe by URL while preserving order
    seen = set()
    unique = []
    for s in cited:
        if s.url not in seen:
            seen.add(s.url)
            unique.append(s)
    return unique[:_MAX_CAPTION_SOURCES]


def build_caption(
    *,
    claim: Claim,
    verdict: Verdict,
    reel: Reel,
    generated: ContentGenerationResult,
    caption_sources: list[Source],
) -> str:
    sources_block = "\n".join(
        f"{i+1}. {s.publisher or s.title or s.url}\n   {s.url}" for i, s in enumerate(caption_sources)
    ) or "No corroborating sources were found at the time of publication."
    return (
        "🔎 FACT CHECK\n\n"
        "CLAIM:\n"
        f'"{claim.text}"\n\n'
        "VERDICT:\n"
        f"{verdict.verdict.value.replace('_', ' ')}\n\n"
        "WHAT WE FOUND:\n"
        f"{generated.caption_what_we_found}\n\n"
        "WHY:\n"
        f"{generated.caption_why}\n\n"
        "SOURCES:\n"
        f"{sources_block}\n\n"
        "ORIGINAL REEL:\n"
        f"{reel.source_url}\n\n"
        "IMPORTANT:\n"
        f"{_IMPORTANT_NOTE}\n\n"
        f"{_HASHTAGS}"
    )


async def generate_content(
    db,
    *,
    claim: Claim,
    verdict: Verdict,
    reel: Reel,
    evidence_rows: list[Evidence],
    sources: list[Source],
) -> tuple[ContentGenerationResult, str, list[Source]]:
    settings = get_settings()
    sources_by_id = {s.id: s for s in sources}
    # Scope strictly to what THIS verdict actually cited — evidence_rows may
    # span multiple research rounds (e.g. after "research again" or when
    # building a correction), and cited_evidence_ids is the only reliable
    # way to know which round a given verdict is actually backed by. No
    # fallback to the unfiltered list: an empty citation set (including the
    # anti-hallucination validator's forced-empty case) means "cite
    # nothing," not "cite everything."
    cited_evidence = [e for e in evidence_rows if e.id in set(verdict.cited_evidence_ids)]

    evidence_summary = "\n".join(
        f"- [{sources_by_id[e.source_id].source_type.value}] {e.stance.value}: {e.explanation}"
        for e in cited_evidence
    )
    user_content = (
        f"CLAIM: {claim.text}\n"
        f"VERDICT: {verdict.verdict.value}\n"
        f"EVIDENCE SUMMARY:\n{evidence_summary}"
    )

    provider = get_llm_provider()
    result = await provider.structured_call(
        model=settings.LLM_MODEL_CONTENT_GENERATION,
        system_prompt=CONTENT_GENERATION_SYSTEM_PROMPT,
        user_content=user_content,
        output_schema=ContentGenerationResult,
        prompt_version=CONTENT_GENERATION_PROMPT_VERSION,
    )

    if settings.LLM_PROVIDER == "ollama" and settings.GEMINI_API_KEY and not _content_looks_complete(result.parsed):
        logger.warning(
            "content_generation_incomplete_retrying_via_gemini",
            claim_id=str(claim.id),
            model=result.model,
        )
        from app.services.ai.gemini_provider import GeminiProvider

        retry_result: LLMCallResult = await GeminiProvider().structured_call(
            model=settings.LLM_MODEL_GEMINI_FALLBACK,
            system_prompt=CONTENT_GENERATION_SYSTEM_PROMPT,
            user_content=user_content,
            output_schema=ContentGenerationResult,
            prompt_version=CONTENT_GENERATION_PROMPT_VERSION,
        )
        await record_audit(
            db,
            entity_type="claim",
            entity_id=claim.id,
            actor_type=ActorType.system,
            actor="content_generation",
            action="content_generation_quality_retry",
            input_summary={"original_model": result.model},
            output_summary={"retry_model": retry_result.model},
        )
        result = retry_result

    caption_sources = _top_sources_for_caption(cited_evidence, sources_by_id)
    caption = build_caption(
        claim=claim, verdict=verdict, reel=reel, generated=result.parsed, caption_sources=caption_sources
    )

    await record_audit(
        db,
        entity_type="claim",
        entity_id=claim.id,
        actor_type=ActorType.ai_stage,
        actor=f"llm:{result.model}",
        action="content_generation",
        input_summary={"cited_evidence_count": len(cited_evidence)},
        output_summary=result.raw_output,
        prompt_version=result.prompt_version,
        tokens=result.token_usage_dict(),
    )
    return result.parsed, caption, caption_sources
