"""Day 10: generate every data figure used in research_paper/main.tex from
real, already-collected result files. Nothing here is estimated or
simulated -- each figure's data source is cited in its own function.
Two numbers (the source-tier and evidence-stance distribution, n=68) are
not currently re-queryable in this environment (no live Postgres
instance -- see REPRODUCIBILITY.md), so they are read from the exact
values already published and cross-checked in
research/EVIDENCE_EVALUATION.md rather than re-derived; this is disclosed
in that function's docstring and in REPRODUCIBILITY.md, not hidden.

Run: python backend/research/day10_figures.py
Writes PDFs to research_paper/figures/.
"""
import csv
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_ROOT / "research" / "results"
RESEARCH_DIR = PROJECT_ROOT / "research"
FIG_DIR = PROJECT_ROOT / "research_paper" / "figures"

plt.rcParams.update({"font.size": 9, "figure.dpi": 150})

_BAR_COLOR = "#4C72B0"
_BASE_COLOR = "#888888"


def _save(fig, name):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    path = FIG_DIR / name
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {path}")


def fig_main_results():
    """Source: research/results/day8_summary.json (regenerated by
    backend/research/day8_final_tables.py from the raw baseline .jsonl
    and full_truthlens_reel_level_day8*.json files). Table 1 (each
    config's own full run) and Table 2 (paired 6-item subset)."""
    summary = json.loads((RESULTS_DIR / "day8_summary.json").read_text())
    t1 = summary["table1_all_9_items"]
    t2 = summary["table2_paired_6_items"]
    configs = ["baseline_1_llm_only", "baseline_2_search_llm", "baseline_3_search_rag_llm", "full_truthlens_n6"]
    t2_configs = ["baseline_1_llm_only", "baseline_2_search_llm", "baseline_3_search_rag_llm", "full_truthlens"]
    labels = ["B1\nLLM-only", "B2\nSearch+LLM", "B3\nSearch+\nRAG+LLM", "Full\nTruthLens"]

    table2_correct = {c: t2[c]["correct"] for c in t2_configs}
    table2_n = t2["full_truthlens"]["n"]

    fig, axes = plt.subplots(1, 2, figsize=(7, 2.8))

    acc1 = [100 * t1[c]["correct"] / t1[c]["n"] for c in configs]
    n1 = [t1[c]["n"] for c in configs]
    axes[0].bar(labels, acc1, color=[_BASE_COLOR] * 3 + [_BAR_COLOR])
    for i, (a, n) in enumerate(zip(acc1, n1)):
        axes[0].text(i, a + 2, f"{a:.1f}%\n(n={n})", ha="center", fontsize=7)
    axes[0].set_ylabel("Accuracy")
    axes[0].set_ylim(0, 100)
    axes[0].set_title("Table 1: each config's own full run")

    acc2 = [100 * table2_correct[c] / table2_n for c in t2_configs]
    axes[1].bar(labels, acc2, color=[_BASE_COLOR] * 3 + [_BAR_COLOR])
    for i, a in enumerate(acc2):
        axes[1].text(i, a + 2, f"{a:.1f}%", ha="center", fontsize=7)
    axes[1].set_ylim(0, 100)
    axes[1].set_title(f"Table 2: paired, same {table2_n} items")

    fig.suptitle("Main comparison -- headline finding", y=1.05)
    _save(fig, "fig2_main_results.pdf")


def fig_decomposition_ablation():
    """Source: research/results/day8_summary.json's table3_claim_decomposition
    block (from backend/research/day8_final_tables.py, reading real,
    already-collected Day 5 verdict data -- no new LLM calls)."""
    summary = json.loads((RESULTS_DIR / "day8_summary.json").read_text())
    t3 = summary["table3_claim_decomposition"]

    def frac_to_pct(s):
        k, n = s.split("/")
        return 100 * int(k) / int(n), n

    single_pct, n = frac_to_pct(t3["single_claim_accuracy"])
    multi_pct, _ = frac_to_pct(t3["multi_claim_accuracy"])

    fig, ax = plt.subplots(figsize=(3.3, 2.8))
    bars = ax.bar(["Single-claim\n(primary only)", "Multi-claim\n(full decomposition)"], [single_pct, multi_pct], color=[_BASE_COLOR, _BAR_COLOR])
    for b, v in zip(bars, [single_pct, multi_pct]):
        ax.text(b.get_x() + b.get_width() / 2, v + 2, f"{v:.1f}%", ha="center", fontsize=8)
    ax.set_ylabel("Accuracy")
    ax.set_ylim(0, 100)
    ax.set_title(f"Claim-decomposition ablation ($n={n}$)")
    _save(fig, "fig3_decomposition_ablation.pdf")


def fig_validator_before_after():
    """Source: research/VALIDATOR_EVALUATION.md's original confusion
    matrix (TP=1,FN=5,FP=0,TN=3) and its addendum re-scored matrix
    (TP=2,FN=3,FP=0,TN=4), n=9 both times, one unadjudicated reviewer."""
    before = {"precision": 100 * 1 / 1, "recall": 100 * 1 / 6}
    after = {"precision": 100 * 2 / 2, "recall": 100 * 2 / 5}

    fig, ax = plt.subplots(figsize=(3.3, 2.8))
    x = [0, 1]
    width = 0.35
    ax.bar([i - width / 2 for i in x], [before["precision"], after["precision"]], width, label="Precision", color=_BASE_COLOR)
    ax.bar([i + width / 2 for i in x], [before["recall"], after["recall"]], width, label="Recall", color=_BAR_COLOR)
    ax.set_xticks(x)
    ax.set_xticklabels(["Before\n(3 checks)", "After\n(+ Check 4)"])
    ax.set_ylim(0, 110)
    ax.set_ylabel("%")
    ax.legend(fontsize=7, loc="upper left")
    for i, (p, r) in enumerate([(before["precision"], before["recall"]), (after["precision"], after["recall"])]):
        ax.text(i - width / 2, p + 2, f"{p:.0f}", ha="center", fontsize=7)
        ax.text(i + width / 2, r + 2, f"{r:.0f}", ha="center", fontsize=7)
    ax.set_title("Validator P/R, $n=9$")
    _save(fig, "fig4_validator_before_after.pdf")


def fig_evidence_quality():
    """Source: research/EVIDENCE_EVALUATION.md's real tier/stance
    distribution table (n=68 Source/Evidence rows, Day 5 live pipeline
    run) and its four-way primary-source metric. These two counts are
    not re-queried live in this environment (no running Postgres
    instance here -- see REPRODUCIBILITY.md); they are the exact,
    already-published, cross-checked values from that document, not
    re-derived or estimated."""
    tiers = {"other": 43, "primary_gov't": 14, "est. news": 6, "primary_legal": 2, "news_wire": 2, "factcheck_org": 1, "primary_data": 0}
    stance = {"irrelevant": 58, "contradicts": 8, "supports": 2, "provides_context": 0}
    four_way = {
        "1. Tier\nclassif.": 16 / 68 * 100,
        "2. Relevant\nprimary": 11 / 16 * 100,
        "3. Fetch\nsuccess*": 16 / 16 * 100,
        "4. Usable\nevidence": 3 / 16 * 100,
    }

    fig, axes = plt.subplots(1, 3, figsize=(7.5, 2.6))
    axes[0].bar(list(tiers.keys()), list(tiers.values()), color=_BAR_COLOR)
    axes[0].set_title("Source tier ($n=68$)")
    axes[0].tick_params(axis="x", rotation=60, labelsize=6)

    axes[1].bar(list(stance.keys()), list(stance.values()), color=_BAR_COLOR)
    axes[1].set_title("Evidence stance ($n=68$)")
    axes[1].tick_params(axis="x", rotation=60, labelsize=6)

    axes[2].bar(list(four_way.keys()), list(four_way.values()), color=_BAR_COLOR)
    axes[2].set_ylim(0, 100)
    axes[2].set_title("Four-way primary-source metric")
    axes[2].tick_params(axis="x", labelsize=6)
    for i, v in enumerate(four_way.values()):
        axes[2].text(i, v + 2, f"{v:.0f}%", ha="center", fontsize=6)

    fig.suptitle("Evidence quality (RQ4)", y=1.05)
    _save(fig, "fig5_evidence_quality.pdf")


def fig_multimodal_coverage():
    """Source: research/MULTIMODAL_EVALUATION.md's claim-coverage table
    ($n=6$, item-0003 excluded, Day 4)."""
    conditions = ["text_only", "text_ocr", "text_ocr_vision\n(full)"]
    covered = [1, 0, 2]
    n = 6
    pct = [100 * c / n for c in covered]

    fig, ax = plt.subplots(figsize=(3.3, 2.8))
    bars = ax.bar(conditions, pct, color=_BAR_COLOR)
    for b, c in zip(bars, covered):
        ax.text(b.get_x() + b.get_width() / 2, 100 * c / n + 2, f"{c}/{n}", ha="center", fontsize=8)
    ax.set_ylabel("Claim coverage")
    ax.set_ylim(0, 100)
    ax.set_title("Coverage by modality (RQ3)")
    _save(fig, "fig6_multimodal_coverage.pdf")


def fig_efficiency():
    """Source: research/system_efficiency.csv (Day 3 baseline smoke
    tests + Day 5 real pipeline run)."""
    rows = list(csv.DictReader((RESEARCH_DIR / "system_efficiency.csv").open()))
    labels, calls = [], []
    for r in rows:
        if r["avg_llm_calls"] in ("not_yet_run",):
            continue
        labels.append(r["config"].replace("_", " "))
        calls.append(float(r["avg_llm_calls"].lstrip("~")))

    fig, ax = plt.subplots(figsize=(4.2, 2.8))
    bars = ax.barh(labels, calls, color=_BAR_COLOR)
    for b, c in zip(bars, calls):
        ax.text(c + 0.1, b.get_y() + b.get_height() / 2, f"{c:g}", va="center", fontsize=7)
    ax.set_xlabel("LLM calls per claim")
    ax.set_title("Efficiency (calls/claim)")
    _save(fig, "fig7_efficiency.pdf")


def fig_rq_status():
    """Source: Table~\\ref{tab:rqs} in main.tex, itself derived from the
    per-RQ status stated across Sections VII-XI; a visual index, not new
    data."""
    rqs = ["RQ1\nValidation", "RQ2\nDecomposition", "RQ3\nMultimodal", "RQ4\nEvidence", "RQ5\nBias", "RQ6\nCalibration"]
    status = [1, 0.5, 0.5, 0.75, 0, 0]  # 1=yes, 0.5=directional/mixed, 0=deferred
    colors = ["#4C9A6A" if s == 1 else ("#D9A441" if s > 0 else "#B0413E") for s in status]

    fig, ax = plt.subplots(figsize=(4.2, 2.8))
    ax.barh(rqs, status, color=colors)
    ax.set_xlim(0, 1.1)
    ax.set_xticks([0, 0.5, 1])
    ax.set_xticklabels(["Deferred", "Directional /\nmixed", "Supported"])
    ax.set_title("RQ status at a glance")
    _save(fig, "fig8_rq_status.pdf")


if __name__ == "__main__":
    fig_main_results()
    fig_decomposition_ablation()
    fig_validator_before_after()
    fig_evidence_quality()
    fig_multimodal_coverage()
    fig_efficiency()
    fig_rq_status()
    print("Note: Fig. 1 (system architecture) is drawn directly in LaTeX via")
    print("TikZ in research_paper/main.tex, not generated by this script.")
