"""initial schema

Revision ID: 23af2f21ff69
Revises: 
Create Date: 2026-08-11 18:22:41.498862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '23af2f21ff69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('ai_stage', 'human', 'system', name='actor_type'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('instagram_accounts',
    sa.Column('ig_user_id', sa.String(length=64), nullable=False),
    sa.Column('ig_username', sa.String(length=255), nullable=True),
    sa.Column('facebook_page_id', sa.String(length=64), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', name='instagram_account_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_user_id')
    )
    op.create_table('reels',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'x', 'tiktok', 'other', name='platform'), nullable=False),
    sa.Column('creator_handle', sa.String(length=255), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('media_storage_key', sa.Text(), nullable=True),
    sa.Column('media_content_hash', sa.String(length=128), nullable=True),
    sa.Column('thumbnail_storage_key', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vision_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovery_source', sa.Enum('manual', 'rss', 'youtube', 'x', 'news', 'factcheck_org', 'tip', name='discovery_source'), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('ingestion_status', sa.Enum('uploaded', 'transcribing', 'transcribed', 'failed', name='ingestion_status'), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reels_media_content_hash'), 'reels', ['media_content_hash'], unique=False)
    op.create_table('claims',
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.Enum('factual', 'opinion', 'prediction', 'satire', 'rhetorical', name='claim_type'), nullable=False),
    sa.Column('verifiable', sa.Boolean(), nullable=False),
    sa.Column('time_reference', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('extraction_model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('extracted', 'researching', 'researched', 'skipped_not_verifiable', name='claim_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_queries',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('target_tier', sa.Enum('tier1_primary', 'tier2_secondary', 'tier3_factcheck', 'unrestricted', name='target_tier'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('raw_response_storage_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdicts',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('TRUE', 'MOSTLY_TRUE', 'MISLEADING', 'MOSTLY_FALSE', 'FALSE', 'UNVERIFIED', 'OUTDATED', 'MISSING_CONTEXT', name='verdict_label'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('very_high', 'high', 'moderate', 'requires_review', name='confidence_band'), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('cited_evidence_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('validation_status', sa.Enum('passed', 'downgraded_missing_citation', 'downgraded_unfetched_source', 'downgraded_unsupported_stat', name='validation_status'), nullable=False),
    sa.Column('verdict_model', sa.String(length=255), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_checks',
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('primary_claim_id', sa.UUID(), nullable=False),
    sa.Column('covered_claim_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('current_verdict_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('researching', 'ready_for_review', 'approved', 'rejected', 'published', 'corrected', 'retracted', name='fact_check_status'), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('methodology_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('duplicate_of_fact_check_id', sa.UUID(), nullable=True),
    sa.Column('public_page_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_verdict_id'], ['verdicts.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_fact_check_id'], ['fact_checks.id'], ),
    sa.ForeignKeyConstraint(['primary_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.Enum('primary_government', 'primary_legal', 'primary_data', 'news_wire', 'established_news', 'academic', 'factcheck_org', 'other', name='source_tier'), nullable=False),
    sa.Column('full_text_storage_key', sa.Text(), nullable=False),
    sa.Column('relevant_passage', sa.Text(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('reliability_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_query_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('fact_check_id', sa.UUID(), nullable=True),
    sa.Column('metric_scope', sa.Enum('post', 'account', 'pipeline', name='metric_scope'), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('website_clicks', sa.Integer(), nullable=True),
    sa.Column('pipeline_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrections',
    sa.Column('fact_check_id', sa.UUID(), nullable=False),
    sa.Column('previous_verdict_id', sa.UUID(), nullable=False),
    sa.Column('new_verdict_id', sa.UUID(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=False),
    sa.Column('new_evidence_source_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('published_correction_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_checks.id'], ),
    sa.ForeignKeyConstraint(['new_verdict_id'], ['verdicts.id'], ),
    sa.ForeignKeyConstraint(['previous_verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.Enum('supports', 'contradicts', 'provides_context', 'irrelevant', name='evidence_stance'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('directness', sa.Enum('direct', 'indirect', name='evidence_directness'), nullable=False),
    sa.Column('analysis_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_posts',
    sa.Column('fact_check_id', sa.UUID(), nullable=False),
    sa.Column('instagram_account_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_checks.id'], ),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_check_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('slides',
    sa.Column('fact_check_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('slide_type', sa.Enum('poster', 'original_reel', 'evidence', 'conclusion', name='slide_type'), nullable=False),
    sa.Column('image_storage_key', sa.Text(), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishing_jobs',
    sa.Column('generated_post_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'containers_created', 'carousel_created', 'publishing', 'published', 'failed', name='publishing_job_status'), nullable=False),
    sa.Column('media_container_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carousel_container_id', sa.String(length=128), nullable=True),
    sa.Column('ig_media_id', sa.String(length=128), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_post_id'], ['generated_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishing_jobs')
    op.drop_table('slides')
    op.drop_table('generated_posts')
    op.drop_table('evidence')
    op.drop_table('corrections')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('fact_checks')
    op.drop_table('verdicts')
    op.drop_table('search_queries')
    op.drop_table('claims')
    op.drop_index(op.f('ix_reels_media_content_hash'), table_name='reels')
    op.drop_table('reels')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
