"""add reels.auto_fetched

Revision ID: 461f46ab44cd
Revises: 23af2f21ff69
Create Date: 2026-08-11 19:24:26.006976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '461f46ab44cd'
down_revision: Union[str, None] = '23af2f21ff69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reels', sa.Column('auto_fetched', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reels', 'auto_fetched')
    # ### end Alembic commands ###
