"""add search_queries.query_type

Revision ID: ad9d67b949f7
Revises: 05807d659a5d
Create Date: 2026-08-18 00:24:25.117230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad9d67b949f7'
down_revision: Union[str, None] = '05807d659a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_query_type_enum = sa.Enum(
    'exact_claim', 'entity_focused', 'primary_source', 'contradiction', 'context_history', 'unspecified',
    name='query_type',
)


def upgrade() -> None:
    # New enum type used via add_column (not create_table) needs an
    # explicit create() first -- same pattern as gemini_task_status in
    # 72b8bd05d670, since add_column alone does not create the
    # underlying Postgres type on its own.
    _query_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'search_queries',
        sa.Column('query_type', _query_type_enum, server_default='unspecified', nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'query_type')
    # ### end Alembic commands ###
