"""add verdicts corrected_fact and context_note

Revision ID: d4b85e87ec45
Revises: f49e55498e6b
Create Date: 2026-08-12 20:29:05.643723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4b85e87ec45'
down_revision: Union[str, None] = 'f49e55498e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verdicts', sa.Column('corrected_fact', sa.Text(), nullable=True))
    op.add_column('verdicts', sa.Column('context_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verdicts', 'context_note')
    op.drop_column('verdicts', 'corrected_fact')
    # ### end Alembic commands ###
